version: "3.8"

services:
  backend-core:
    image: backend-base:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    pull_policy: never
    env_file:
      - .env
    build:
      context: backend
      dockerfile: Dockerfile.dev
      cache_from:
        - backend-base:latest
      args:
        - DEV_MODE=true
    container_name: backend-core
    volumes:
      - ./backend/:/code/
    command:
      - "uvicorn"
      - "main:app"
      - "--reload"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "5050"
      - "--log-level"
      - "info"
    restart: always

    ports:
      - 5050:5050
      - 5678:5678 # debug port
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-core.rule=Host(`dev.wildcatgpt.com`) && PathPrefix(`/backend_core`)"
      - "traefik.http.routers.backend-core.entrypoints=websecure"
      - "traefik.http.routers.backend-core.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend-core.loadbalancer.server.port=5050"
      - "traefik.http.middlewares.backend-core-stripprefix.stripprefix.prefixes=/backend_core"
      - "traefik.http.routers.backend-core.middlewares=backend-core-stripprefix"

  redis:
    image: redis:latest
    container_name: redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - 6379:6379

  worker:
    pull_policy: never
    image: backend-base:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    container_name: worker
    # volumes:
    #   - ./backend/:/code/
    command: celery -A celery_worker worker -l info
    restart: always
    depends_on:
      - redis

  beat:
    image: backend-base:latest
    pull_policy: never
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env

    container_name: beat
    command: celery -A celery_worker beat -l info
    restart: always
    depends_on:
      - redis

  flower:
    image: backend-base:latest
    pull_policy: never
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env

    container_name: flower
    command: celery -A celery_worker flower -l info --port=5555
    restart: always
    depends_on:
      - redis
      - worker
      - beat
    ports:
      - 5555:5555

  traefik:
    image: traefik:v2.4
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesResolvers.letsencrypt.acme.email=cale@modtechgroup.com"
      - "--certificatesResolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesResolvers.letsencrypt.acme.tlsChallenge=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Traefik Dashboard (optional, but useful for debugging)
    networks:
      - default
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/letsencrypt:/letsencrypt"
    restart: always
